### ISSUE TITLE
Homework_1

### ISSUE THREAD

**Issue by lsumabat** [lsumabat/gene8940#2]
To create a new issue on Github and perform first Gene8940 homework

**Comment by lsumabat** [comment]
a. Overall goal of my thesis project is to understand cause of disease emergence of target spot of cotton, soybean, and tomato caused by *Corynespora cassiicola* in the southeastern U.S. One aspect of my project includes conducting comparative genomics analysis among previously identified populations of *C. cassiicola*, particularly the genes that encode for necrotrophic effectors which could be involved in the determined population structure.
b. I have performed a few population genetics analysis through software programs that are of command-line interface (in R). However, I haven't been able to perform tasks with whole genome data.
c. Generally, to gain bioinformatics tools and practical skills to efficiently run whole genome analysis and consequently be able to interpret the results, through hands-on experiences such as in-class and homework activities. Specifically, my interest would include approaches in genome assembly, annotation, molecular databases access, SNP analysis, and comparative genomics.

**Comment by cbergman** [comment]
- Thanks for this info, I'll try to make sure we cover most of these topic in the course. 
- Be sure to click the eye button at the top of the page to get all notifications for this repository
- Grade: 10/10

**Comment by cbergman** [comment]
- also, be sure to make this repository private
